### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by schmermeister** [Graylog2/gelfclient#47]
Hello,

using 1.5.0 (1.4.0) throws java.lang.NoSuchMethodError: io.netty.channel.nio.NioEventLoopGroup():

`java.lang.NoSuchMethodError: io.netty.channel.nio.NioEventLoopGroup.<init>(ILjava/util/concurrent/ThreadFactory;)V
	at org.graylog2.gelfclient.transport.AbstractGelfTransport.<init>(AbstractGelfTransport.java:41)
	at org.graylog2.gelfclient.transport.AbstractGelfTransport.<init>(AbstractGelfTransport.java:62)
	at org.graylog2.gelfclient.transport.GelfUdpTransport.<init>(GelfUdpTransport.java:49)
	at org.graylog2.gelfclient.GelfTransports.create(GelfTransports.java:45)
	at org.graylog2.gelfclient.GelfTransports.create(GelfTransports.java:61)
...

Already added netty-all dependency, but errro stil occurs.

How can i solve it?

Thanks in advance.

**Comment by jalogisch** [comment]
he @schmermeister 

could you please be a little more verbose what you actually did and how you tried to use this?
